fixtures:
  forge_modules:
    artifactory: "evenup/artifactory"
    concat:
      repo: "puppetlabs/concat"
      ref: "1.1.0"
    java:
      repo: "puppetlabs/java"
      ref: "1.0.0"
    staging: "nanliu/staging"
    stdlib: "puppetlabs/stdlib"
  symlinks:
    tomcat: "#{source_dir}"
