---
  .travis.yml:
    hc_secure: "bBFhBYzEQqIH29VtahTQD+28xka3Ywx3cdBHBmwq8UUuTjcMJJU5ecQRr/icAWQ3n5f8F4PIjkq8YYFc8/dKy52yrKtg/CxrdcaDTF0FDHRjw2WhKVdCvv9SNQfqO9wSxAFiqJI1ed+5OKiVH9JZ9mY4UgnX1+mG2alVtnMjXj8="

