---
  .travis.yml:
    hc_secure: "rlfAny8f0Nkofxrj5WFWiABV9Z+c7FAtlxW2ofEfx6k/64UmT1kYpgHa+9W+\neEHvpcTOZ58WaXMX9uDXiav9R1LKMJ6Ro+mtWbw5qZeUq7hhb2JShBpOgl0g\nkueDqg7pZLfCc1p7bcOCgSzK1w7vuXEqHxZUElGy8GkMlFXkrKw="

